export { default as Logo } from "./logo.png";
export { default as IWatch } from "./images/iwatch.png"
export { default as Tablet } from "./images/tablet.png"
export { default as IPad } from "./images/ipad.png"
export { default as AirPods } from "./images/airpods.png"
export { default as HeadPhones } from "./images/headphones.png"
export { default as SmartWatch } from "./images/smartwatch.png"
export { default as Phone } from "./images/phone.png"
export { default as Pipes } from "./images/pipes.png"